check_function_exists(asprintf HAVE_ASPRINTF)
if(HAVE_ASPRINTF)
    add_definitions("-DHAVE_ASPRINTF=1")
else()
    message(STATUS "asprintf is missing, using missing/asprintf.c")
    set(MISSING_C ${MISSING_C} src/missing/asprintf.c)
endif()

check_function_exists(strlcat HAVE_STRLCAT)
if(HAVE_STRLCAT)
    add_definitions("-DHAVE_STRLCAT=1")
else()
    message(STATUS "strcat is missing, using missing/strcat.c")
    set(MISSING_C ${MISSING_C} src/missing/strlcat.c)
endif()

check_function_exists(strlcpy HAVE_STRLCPY)
if(HAVE_STRLCPY)
    add_definitions("-DHAVE_STRLCPY=1")
else()
    message(STATUS "strlcpy is missing, using missing/strlcpy.c")
    set(MISSING_C ${MISSING_C} src/missing/strlcpy.c)
endif()

check_function_exists(strtok_r HAVE_STRTOK_R)
if(HAVE_STRTOK_R)
    message(STATUS "strtok is presented")
    add_definitions("-DHAVE_STRTOK_R=1")
else()
    message(STATUS "strtok_r is missing, using missing/strtok_r.c")
    set(MISSING_C ${MISSING_C} src/missing/strtok_r.c)
endif()

mark_as_advanced(MISSING_C)
